In [101]:
import numpy as np

In [131]:
import numpy as np

arr = np.array([12, 23, 34, 56, 23])

In [132]:
arr

array([12, 23, 34, 56, 23])

In [133]:
print(arr)

[12 23 34 56 23]


In [134]:
type(arr)

numpy.ndarray

In [135]:
datatype = arr.dtype
print(datatype)

int32


In [136]:
arr

array([12, 23, 34, 56, 23])

In [137]:
import numpy as np

arr = np.array([12, 23, 45, 56, 32, 66, 22, 'Pune'])

In [138]:
arr

array(['12', '23', '45', '56', '32', '66', '22', 'Pune'], dtype='<U11')

In [139]:
import numpy as np
import timeit

# Define the code snippet you want to measure
code_snippet = """
arr = np.array([12, 23, 45, 56, 32, 66, 22, 'Pune'])
"""

# Measure the execution time
execution_time = timeit.timeit(stmt=code_snippet, setup="import numpy as np", number=1)

print("Execution time:", execution_time)

Execution time: 3.600001218728721e-05


In [140]:
arr[3]

'56'

In [141]:
arr.shape

(8,)

In [142]:
import numpy as np

arr = np.array([12, 23, 45, 56, 32])
print(arr)

[12 23 45 56 32]


In [143]:
arr * 2

array([ 24,  46,  90, 112,  64])

In [144]:
import numpy as np

arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [145]:
import numpy as np

arr = np.arange(2, 10)
print(arr)

[2 3 4 5 6 7 8 9]


In [146]:
import numpy as np

arr = np.arange(-5, 5.5, 0.5)
print(arr)

[-5.  -4.5 -4.  -3.5 -3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5
  2.   2.5  3.   3.5  4.   4.5  5. ]


In [147]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [148]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [149]:
# 2d

In [150]:
arr1 = np.array([[1,2,3], [4,5,6],[7,8,9],[10,11,12]])

In [151]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [152]:
arr1.shape

(4, 3)

In [153]:
arr1.ndim

2

In [154]:
arr1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [156]:
arr1.reshape

<function ndarray.reshape>

In [157]:
arr1.size

12

In [158]:
arr1.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [159]:
arr1.reshape(6, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [160]:
arr1.reshape(6, -1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [161]:
arr1.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [162]:
arr1.reshape(4,3,-1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [163]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [164]:
arr1[0:3, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [165]:
arr1.mean()

6.5

In [166]:
arr1 = np.array([1,3,6,3,3,1,7])

In [167]:
np.unique(arr)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [168]:
arr1 = np.array([[1,2,3], [4,5,6],[7,8,9]])
arr2 = np.array([[1,2,3], [4,5,6],[7,8,9]])
arr

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [169]:
np.linalg.det(arr1)

-9.51619735392994e-16

In [170]:
np.linalg.inv(arr1)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [171]:
arr1 @ arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [172]:
arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])